version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4-buster
    steps:
      - checkout
      - run:
          command: |
            pwd
            pip install ~/midi-webmixer/
